spring.application.name=MMorpgApi
# Usar banco H2 em memória
spring.datasource.url=${DATABASE_URL}
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

# Mostrar SQL no console (opcional, para debug)
spring.jpa.show-sql=true

# Criar/Atualizar o esquema automaticamente
spring.jpa.hibernate.ddl-auto=update

# Habilitar console web do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console